version: '3'

services:
  # Node.js and Express application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecardify
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongodb_ecardify
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}

